services:

  odoo:
    image: odoo:16.0
    restart: always
    depends_on:
      - db
    ports:
      - "80:8069"
    deploy:
      resources:
        limits:
          cpus: "1.0"  # Limits Odoo to use 1 CPU core
        reservations:
          cpus: "0.5"  # Reserves 0.5 CPU cores for Odoo


  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data

  # nginx:
  #   image: nginx:latest
  #   depends_on:
  #     - odoo
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   networks:
  #     - odoo_network

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done'"


volumes:
  odoo_data:
  odoo_custom_addons:
  db_data: