services:

  odoo:
    build:
      context: .
      dockerfile: Dockerfile.odoo
    restart: always
    depends_on:
      - db
    ports:
      - "80:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./odoo-allinoneaccessibility:/mnt/extra-addons/odoo-allinoneaccessibility
    deploy:
      resources:
        limits:
          cpus: "1.0"  # Limits Odoo to use 1 CPU core
        reservations:
          cpus: "0.5"  # Reserves 0.5 CPU cores for Odoo

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data

volumes:
  odoo_data:
  odoo_custom_addons:
  db_data:
